itemsLoad = function(itemsIterate){
  let valuesGrabbed = "";
  for(let valueGrab in itemsIterate[0]){
      valuesGrabbed += (itemsIterate[1][valueGrab] > 0 ? "x"+itemsIterate[1][valueGrab]+"  " : "")+(itemsIterate[0][valueGrab] < 10 ? items[itemsIterate[0][valueGrab]].name : itemsIterate[0][valueGrab].split("_").join(" "))+"\n"
  }
    //alert(valuesGrabbed);
  return valuesGrabbed
}

imgMake = function(path){
    let img = new Image();
    img.src = "images/bugs/"+path+".png";
    return img
}

const facilities = {
 0:{
 name: "Command Center",
 descp: "A small barren field created for\ndeploying bugs for missions. New\nmissions can be found often here.\n(Requires: Full Health, Age 50+)",
 miscIndex: 6,
 filter: nameSearch => nameSearch.Age >= 50 && nameSearch.Health == nameSearch.HealthTotal && battleBugs.indexOf(nameSearch) == -1,
 infoScreen: true,
 },
 1:{
 name: "Smuggler Junkyard",
 descp: "Suspicious land where bugs vanish\nleaving only territs behind. Myths\nforetell paradise is what awaits.",
 miscIndex: 59,
 filter: nameSearch => nameSearch.Health > 0,
 infoScreen: false,
 },
 2:{
 name: "Territ Stronghold",
 descp: "A hidden stronghold where Territs\nare gathered in obscure ways.\n(Requires: Intelligence, Age 50+)\n(Bonus: Snowstorms)",
 miscIndex: 45,
 filter: nameSearch => (nameSearch.Age >= 50 && nameSearch.AlignmentsText[1] > 0) || nameSearch.Patrol == rooms[boxSelector.substr(21)],
 infoScreen: false,
 },
 3:{
 name: "Nectar Grove",
 descp: "A lush orchard where nectar is\nharvested from tree sap with an\naverage food output.\n(Requires: Intelligence, Age 50+)",
 miscIndex: 47,
 filter: nameSearch => (nameSearch.Age >= 50 && nameSearch.AlignmentsText[1] > 0) || nameSearch.Patrol == rooms[boxSelector.substr(21)],
 infoScreen: false,
 },
 4:{
 name: "Luminescent Cavern",
 descp: "A damp cavern where fungus is\nharvested from crevices with a\nbelow average food output.\n(Requires: Intelligence, Age 50+)\n(Bonus: Drizzle & Thunderstorms)",
 miscIndex: 52,
 filter: nameSearch => (nameSearch.Age >= 50 && nameSearch.AlignmentsText[1] > 0) || nameSearch.Patrol == rooms[boxSelector.substr(21)],
 infoScreen: false,
 },
 5:{
 name: "Love Field",
 descp: "A small field where bugs can show\ntheir appreciation for eachother,\ncreating infant bugs.\n(Requires: Needed Health, Age 50+)",
 miscIndex: 44,
 filter: nameSearch => (nameSearch.Health >= nameSearch.HealthTotal*(1-nameSearch.AlignmentsText[0]/200) && nameSearch.Age >= 50) || nameSearch.Patrol == rooms[boxSelector.substr(21)],
 infoScreen: false,
 },
 6:{
 name: "Vitality Field",
 descp: "A small field where bugs relax. The\nfield is full of healing clovers which\nassist in the healing process.",
 miscIndex: 63,
 filter: nameSearch => nameSearch.Health <= nameSearch.HealthTotal || nameSearch.Patrol == rooms[boxSelector.substr(21)],
 infoScreen: false,
 },
 7:{
 name: "Life Field",
 descp: "A small field where bugs relax. The\nfield is full of aging clovers which\nassist in the aging process.",
 miscIndex: 60,
 filter: nameSearch => nameSearch.Health >= 0,
 infoScreen: false,
 },
 8:{
 name: "Water Dome",
 descp: "A large dome filled with fresh\nwater suited for recovering\naquatic bugs.\n(Requires: Aquatic Bugs)",
 miscIndex: 55,
 filter: nameSearch => bugStats[nameSearch.Species].swimAble || nameSearch.Patrol == rooms[boxSelector.substr(21)],
 infoScreen: false,
 },
 9:{
 name: "Air Dome",
 descp: "A large dome filled with fresh\nair suited for recovering aerial\nbugs.\n(Requires: Aerial Bugs)",
 miscIndex: 58,
 filter: nameSearch => bugStats[nameSearch.Species].flyAble || nameSearch.Patrol == rooms[boxSelector.substr(21)],
 infoScreen: false,
 }
}

items = {
 0:{
 name: "Nectar Stick",
 descp: "(+100 food)\nA small stick of quality nectar found and harvested in the wild.\nContains various nutrients and is edible by almost all species of bugs.",
 quantity: 0,
 bulk: 0,
 },
 1:{
 name: "Nectar Branch",
 descp: "(+1000 food)\nA large stick of quality nectar found and harvested in the wild.\nContains various nutrients and is edible by almost all species of bugs.",
 quantity: 0,
 bulk: 0,
 },
 2:{
 name: "Thornstump Fruit",
 descp: "(Fully increases desired bug's passiveness)\nAn exceptionally soft fruit ironically edged with a multitude of\nthorny leaves. It's known to improve fertility.",
 quantity: 0,
 price: 500,
 filter: nameSearch => nameSearch.Alignments !== 90,
 action: ["Alignments",90],
 },
 3:{
 name: "Twinbear Berry",
 descp: "(Fully increases desired bug's intelligence)\nA rather large berry that is cool to the touch. The bittersweet\nflavor maxes a bug's intelligence.",
 quantity: 0,
 price: 500,
 filter: nameSearch => nameSearch.Alignments !== 180,
 action: ["Alignments",180],
 },
 4:{
 name: "Porous Screecher",
 descp: "(Fully increases desired bug's aggressiveness)\nA medium sized tuber found deep within barren lands. Distant aggravating noises\nthat resemble that of a banshee erupt from the thin pores.",
 quantity: 0,
 price: 500,
 filter: nameSearch => nameSearch.Alignments !== 270,
 action: ["Alignments",270],
 },
 5:{
 name: "Healing Clover",
 descp: "(Fully heals desired bug)\nA clover pouring with restorative energy. By eating one whole,\na bug can fully recover itself instantly.",
 quantity: 0,
 filter: nameSearch => nameSearch.Health < nameSearch.HealthTotal,
 action: ["Health","HealthTotal"],
 },
 6:{
 name: "Aging Clover",
 descp: "(Fully ages desired bug)\nA clover pouring with life energy. By eating one whole,\na bug can fully mature in the blink of an eye.",
 quantity: 0,
 filter: nameSearch => nameSearch.Age < 100,
 action: ["Age",100],
 },
 7:{
 name: "Trait Modifier",
 descp: "(Randomizes desired bug's trait for fully aged bugs)\nA supplement that partially erases a bug's learned traits\nforcing them to learn a different one.",
 quantity: 0,
 price: 1000,
 filter: nameSearch => nameSearch.Age == 100,
 action: ["Trait","Randomize"],
 },
 8:{
 name: "Gene Modifier",
 descp: "(Toggles desired bug's albinism for fully aged bugs)\nReleases a chemical when drunk that modifies the\ndrinker's cells dealing with light refracting.",
 quantity: 0,
 price: 5000,
 filter: nameSearch => nameSearch.Age == 100,
 action: ["Albino","!Albino"],
 },
 9:{
 name: "Slouching Miracle",
 descp: "(Makes desired bug immortal)\nAn exotic flower that harbors regenerative bacteria which strengthen a\ndrinker's cells, allowing them to recover from any lethal situation.",
 quantity: 0,
 price: 10000,
 filter: nameSearch => !nameSearch.Immortal,
 action: ["Immortal",true],
 }
}

const missions = {
 0:{
 name: "Corntill Plains",
 descp: "A rival nest in the prairie outskirts has suddenly\ngotten hostile. Dethroning Queen Fantasia is our\nonly option before our stores become at stake.",
 type: "Nest",
 difficulty: 50,
 primary: "Ant",
 secondary: "Ant",
 companion: ["Teresa","Termite","Female",225,6],
 },
 1:{
 name: "Corntill Crown",
 descp: "We've reached the queen's capital. Our\nresources are starting to dry up, but they'll\nlast if the encounter is handled properly.",
 type: "Nest",
 difficulty: 50,
 primary: "Ant",
 secondary: "Ant",
 companion: ["Teresa","Termite","Female",225,6],
 queenName: "Queen Fantasia",
 queenFlavor: [["Queen Fantasia","Ant","I would've never guessed a Terrachian would've made it this far. While\nour family is out here starving you thieves decided to break the contract?"],["Teresa","Termite","It had to be done Fantasia. We couldn't take the risk of the water dwellers\nexploiting it with the blight. You know the dangers it could've caused don't you?"],["Queen Fantasia","Ant","I do Teresa, but this cannot justify what your colony has done! Those children\n- no matter. What's done is done. I'm guessing your troops came for me?"],["Queen Fantasia","Ant","There's nowhere to escape isn't there? You Terrachians are good at one\nthing, dying."]],
 },
 2:{
 name: "Engorged Core",
 descp: "Our colony is in need of more resources. A\nhive controlled by bees is a great place to start!\nI suggest to use troops that can fly commander.",
 type: "Hive",
 difficulty: 50,
 primary: "Bee",
 secondary: "Fly",
 },
 3:{
 name: "Weepers' Creek",
 descp: "Weepers' Creek has all the fungi we need to make a\nLuminescent Cavern! It's certainly a dangerous\nplace for us Terrachians, but nothing we can't handle.",
 type: "Pond",
 difficulty: 50,
 primary: "Diving_Beetle",
 secondary: "Mosquito",
 },
 4:{
 name: "Hivemind",
 descp: "Queen Stingeris, the queen of a hive superpower\nhas been hoarding nectar deep within the\nwestern forests. Is this the right decision?",
 type: "Hive",
 difficulty: 50,
 primary: "Bee",
 secondary: "Bee",
 queenName: "Queen Stingeris",
 queenFlavor: [["Queen Stingeris","Bee","It looks like to me child you're not from around these parts? Perhaps, your\none of those Terrachians..."],["Queen Stingeris","Bee","I wouldn't blame you, in fact I would congratulate you. Now, would you\nvillains be so kind to return our precious nectar?"]],
 },
 5:{
 name: "Lament Canal",
 descp: "Lament Canal, one of the saddest excuses of a canal.\nRecently, a rival pondskater colony has been\nattempting to take control of the pond.",
 type: "Pond",
 difficulty: 100,
 primary: "Diving_Beetle",
 secondary: "Mosquito",
 companion: ["Great Typhoon","Pondskater","Female",270,3],
 },
 6:{
 name: "Lament Throneroom",
 descp: "Interestingly enough, one of the original water\ndwellers, Lament, lives in the canal. What exactly\nare they up to?",
 type: "Pond",
 difficulty: 100,
 primary: "Pondskater",
 secondary: "Pondskater",
 queenName: "Queen Lament",
 queenFlavor: [["Queen Lament","Pondskater","I would've never of thought a Terrachian would venture this far out. Listen,\nI know what you're thinking."],["Queen Lament","Pondskater","The water dwellers aren't here to exploit the blight. In fact, the blight hasn't\neven reached us!"],["Queen Lament","Pondskater","I know your kind, you and your lies. I would've allowed you to go peacefully."],["Queen Lament","Pondskater","You see though, those fungi were the only food we had left. You know how\nlong it takes to grow enough to fill a cavern?"],["Queen Lament","Pondskater","Of course you don't. If you did Fantasia and Stingeris would've still been here.\nWho am I supposed to rely on now? You?"]],
 },
 7:{
 name: "Spruce Peak",
 descp: "We interrogated some of the water dwellers.\nThey pointed us towards Spruce Peak? The\nwestern forests have been unhabited for years?",
 type: "Skies",
 difficulty: 100,
 primary: "Butterfly",
 secondary: "Butterfly",
 queenName: "Queen Butterfly",
 queenFlavor: [["Queen Butterfly","Butterfly","Who are you? Are you one of them? Please! Stay Away!"],["Queen Butterfly","Butterfly","I'm warning you."]],
 },
 8:{
 name: "Pressure Zone",
 descp: "The compact air in this forest is remarkable.\nIf we gather enough air we may be able\nto create an Air Dome.",
 type: "Skies",
 difficulty: 100,
 primary: "Butterfly",
 secondary: "Butterfly",
 },
 9:{
 name: "A Case of Webs",
 descp: "With Teresa's help we were able to locate\nmercenaries in the eastern prairies. Let's hope\nwe get what we were looking for.",
 type: "Prairie",
 difficulty: 100,
 primary: "Spider",
 secondary: "Spider",
 queenName: "Queen Widow",
 queenFlavor: [["Queen Widow","Spider","Teresa? Blight? I'll tell you something - she's not who you think she is."],["Queen Widow","Spider","You're good as dead anyway, I might as well spill the beans. Stinge-"],["Queen Widow","Spider","Were you expecting something? I know who you are, you probably have a\nplan to crush all of us at once don't you?"],["Queen Widow","Spider","You're in luck, at this very moment colonies are being dismantled and\ndestroyed. Nectarne is as good as gone!"]],
 },
 10:{
 name: "Arthropod Predators",
 descp: "The once peaceful nests have been overrun by\ncentipedes. Clearly, this is a planned\nattack. Centipedes are usually territorial.",
 type: "Nest",
 difficulty: 150,
 primary: "Centipede",
 secondary: "Centipede",
 },
 11:{
 name: "Primal Predators",
 descp: "The deeper we head into their nest the\nstranger the situation becomes. Who are they\nhunting and why?",
 type: "Nest",
 difficulty: 150,
 primary: "Centipede",
 secondary: "Centipede",
 companion: ["Mediocrity","Millipede","Female",0,0],
 queenName: "Queen Centaury",
 queenFlavor: [["Queen Centaury","Centipede","I've been watching your movements for quite some time. Are you wondering\nwhere this nest's farmers went?"],["Queen Centaury","Centipede","These bugs became too reliant on others. All it would take is one siege\nto take them all down."],["Queen Centaury","Centipede","I'm not the head of this plan, not at all. We collectively will accomplish what\nshould've happened in the first place."],["Queen Centaury","Centipede","Would you like to see? What primordial power looks like?"]],
 },
 12:{
 name: "Hadal Zone",
 descp: "The water in this pond is remarkably refreshing!\nLet's take it back to Nectarne before we\nmake any further moves.",
 type: "Pond",
 difficulty: 150,
 primary: "Giant_Water_Bug",
 secondary: "Giant_Water_Bug",
 companion: ["Nessie","Giant_Water_Bug","Female",135,2],
 },
 13:{
 name: "Primal Power",
 descp: "A tarantula camp was located east of Nectarne\nwith the help of Teresa. Let's make this fast!",
 type: "Prairie",
 difficulty: 150,
 primary: "Tarantula",
 secondary: "Tarantula",
 companion: ["Teresa","Termite","Female",225,6],
 queenName: "Queen Trapper",
 queenFlavor: [["Queen Trapper","Tarantula","Are you looking for a way to end the blight? It's too late, we've taken out most\nof the farmers."],["Teresa","Termite","They didn't deserve to die?"],["Queen Trapper","Tarantula","Who said we killed them? We simply contained them. Killing them would be\npointless, they're the ones that need us the most."],["Teresa","Termite","How about those non-farmers, how will they survive?"],["Queen Trapper","Tarantula","Your slow my dear? You are a termite afterall. Survival of the fittest, if they\nhave to rely on others for food what is their existance for?"],["Queen Trapper","Tarantula","Their primal potenial is locked up. This is why we bugs are looked down upon!"],["Queen Trapper","Tarantula","If you lowlings can take me out. I might be able to make an arrangement. That\nis to say you ever stood a chance."]],
 },
 14:{
 name: "Queen Blackjacket",
 descp: "With the info we got from Trapper we were able to\ntrack Blackjacket and the farmers. It seems as\nthough the water dwellers were right?",
 type: "Skies",
 difficulty: 150,
 primary: "Wasp",
 secondary: "Dragonfly",
 companion: ["Teresa","Termite","Female",225,6],
 queenName: "Queen Blackjacket",
 queenFlavor: [["Queen Blackjacket","Wasp","My my, i'm impressed with the lengths you've gone to get to me. Here you\nlowlings were thinking the blight was naturally caused!"],["Queen Blackjacket","Wasp","It really shows how reliant you all really are. These farmers have and always\nwill be self-sufficient."],["Queen Blackjacket","Wasp","There's no point in hiding it. You Terrachians are strong."],["Queen Blackjacket","Wasp","Its clear to me we haven't thought this through. How about we ignore your\ncolony completely and you ignore us?"],["Teresa","Termite","Your plan is affecting all colonies highness."],["Queen Blackjacket","Wasp","That's true. Let's arrange a deal. Show me how powerful dependent bugs can\nbe and we'll ignore all the surrounding colonies? Yes?"]]
 },
 15:{
 name: "The Undertakers",
 descp: "An underground crossroad where both termites\nand ants colonize. Their synergy leaves\ntravelers paralyzed with fear.",
 type: "Nest",
 difficulty: 50,
 primary: "Termite",
 secondary: "Ant",
 },
 16:{
 name: "Signal Flare",
 descp: "Fireflies aren't exactly tough or weak, our\ntroops can handle them easily. In fact, this'll\nbe a breeze.",
 type: "Nest",
 difficulty: 50,
 primary: "Firefly",
 secondary: "Fly",
 queenName: "Queen Firefly",
 },
 17:{
 name: "Hive Attack",
 descp: "A sister hive of the one in Engorged Core.\nUnlike it, the queens of this colony always\nput up a fight.",
 type: "Hive",
 difficulty: 50,
 primary: "Bee",
 secondary: "Fly",
 queenName: "Queen Bee",
 },
 18:{
 name: "Flutter Sting",
 descp: "Butterflies aren't what we should be worried\nabout. These bees are known to swarm intruders,\nleaving them helpless against their proboscises",
 type: "Hive",
 difficulty: 50,
 primary: "Butterfly",
 secondary: "Bee",
 queenName: "Queen Butterfly",
 },
 19:{
 name: "Dusk Pond",
 descp: "Dusk Pond never sees the light of day; thats\nwhat travelers would say. In fact, the bugs refuse\nto look at the light, seeing it as treacherous.",
 type: "Pond",
 difficulty: 50,
 primary: "Mosquito",
 secondary: "Mosquito",
 },
 20:{
 name: "Offensive Defense",
 descp: "Sometimes the best offense is a good defense.\nThese southern millipedes are proof of that...",
 type: "Nest",
 difficulty: 100,
 primary: "Millipede",
 secondary: "Millipede",
 queenName: "Try Me",
 },
 21:{
 name: "Ambush-Ambush",
 descp: "In some colonies, predators exist because no one\nknows they're there. Mantasy is one\nof those colonies.",
 type: "Hive",
 difficulty: 100,
 primary: "Mantis",
 secondary: "Bee",
 companion: ["Beeuty","Bee","Male",180,5],
 queenName: "Queen Mantis",
 },
 22:{
 name: "Big Mic",
 descp: "Our scouts managed to find the legendary\ntown, Big Mic. A feisty fellow that sworn he's\npart of the local mafia is willing to guide us...",
 type: "Pond",
 difficulty: 100,
 primary: "Diving_Beetle",
 secondary: "Pondskater",
 companion: ["Terry Big Mic","Firefly","Male",359,1],
 },
 23:{
 name: "Leap of Faith",
 descp: "In the peak of the western spruces lives a colony\nof daredevils that can take on any challenge.\nSome though, may not come out alive.",
 type: "Skies",
 difficulty: 100,
 primary: "Spider",
 secondary: "Spider",
 queenName: "Queen Spider",
 },
 24:{
 name: "Cat & Mouse",
 descp: "Rangers and cowards, the nickname of a\nprairie where large grotesque bugs and\nassassins coexist.",
 type: "Prairie",
 difficulty: 100,
 primary: "Scorpion",
 secondary: "Weta",
 companion: ["Tom","Weta","Male",90,4],
 },
 25:{
 name: "Million Cents",
 descp: "Deep within the southern burrows lives a colony,\nso furious and insane, that all that enters fate\nis sealed.",
 type: "Nest",
 difficulty: 150,
 primary: "Millipede",
 secondary: "Centipede",
 queenName: "Miss Millaury",
 queenFlavor: [["???","Millipede","Were you expecting Centaury little one? I'm afraid she passed awhile\nago. News doesn't travel fast around these parts."],["Miss Millaury","Millipede","I can see the gleam in your eyes. You're planning to take her brood? Aha, well\nthen. Try stopping Miss Millaury Terrachian!"]],
 },
 26:{
 name: "Thousand Stingers",
 descp: "A colony of bees, wasps, and all fiends with\nstingers. Trespassers are said to be guided\ndazed after painful stings to be roasted alive.",
 type: "Hive",
 difficulty: 150,
 primary: "Wasp",
 secondary: "Bee",
 queenName: "Queen Blackjacket",
 queenFlavor: [["Queen Blackjacket","Wasp","What brings you here Terrachian? Was the taste of our collective stingers\nnot enough? Perhaps, a thousand more will suffice!"]],
 },
 27:{
 name: "Watery Grave",
 descp: "Where shallow waters end is where the\nfabled queen lays. How long has it been\nsince the last treacherous journey to her domain?",
 type: "Pond",
 difficulty: 150,
 primary: "Giant_Water_Bug",
 secondary: "Pondskater",
 queenName: "Queen Sapphirian",
 queenFlavor: [["Queen Sapphirian","Giant_Water_Bug","Little bug, was I worth this journey? Don't tell me you went on this adventure\njust for me and not for my children. I'm afraid, that's just not happening."]],
 },
 28:{
 name: "Dragons' Roost",
 descp: "High in the western forests is a migratory group\ncalled the Draconians. By fall, they'll move\ninwards to acommodate for food scarcity...",
 type: "Skies",
 difficulty: 150,
 primary: "Dragonfly",
 secondary: "Fly",
 queenName: "Queen Draconian",
 queenFlavor: [["Queen Draconian","Dragonfly","All that flies are strong. All that walk are weak. Those flies you saw, they\naren't like you. They can become better. They can do better. You, you cannot!"]],
 },
 29:{
 name: "Trappers' Quarrel",
 descp: "A secluded prairie located east of Nectarne is home\nto vile beings that call themselves trappers. A\nfew of our farms were salvaged by them, it's time.",
 type: "Prairie",
 difficulty: 150,
 primary: "Tarantula",
 secondary: "Spider",
 queenName: "Queen Trapper",
 queenFlavor: [["Queen Trapper","Tarantula","It never ceases to amaze me how you Terrachians always manage to break\nfree out of our finely crafted webs. What is it about you? Let's have a look."]],
 }
}

const traitDescp = [
    ["Neutrality", "silver", "Recovers 6 health per\nsecond by standing still in\n    battles."],
    ["Irritable", "crimson", "Maxes fury when health\nreaches 25% or less."],
    ["Stockpiler", "coral", "Maintains health during\nfamines."],
    ["Rapacious", "gold", "Doubles territs earned\nthrough battles."],
    ["Supportive", "springGreen", "Halves health lost when\nin love."],
    ["Stalwart", "steelBlue", "Removes slow downs,\nintimidations, and poisons\n    by attacking in battles."],
    ["Trickster", "darkOrchid", "Doubles the duration of\nslow downs, intimidations,\n    and poisons."]
];

const skillDescp = {
    "???" : "This bug is not mature enough to use\na skill",
    "Mandible Press" : "Fury attacks quadruple attack\ninstead of doubling it",
    "Saliva Salvo" : "Spits sticky saliva. Damage is\nhalved, however targets\nare slowed down for 2 seconds",
    "Noxious Whimper" : "Spits distasteful chemicals. Damage is\nhalved, however targets\nare intimidated for 2 seconds",
    "Life Meal" : "Fury attacks restore health based\non the damage output instead\nof doubling attack damage",
    "Stridulating Retreat" : "Leaps during fury attacks after\ncreating a soundwave. Nearby enemies\nare intimidated for 2 seconds.",
    "Defensive Coil" : "Coils can be maintained by holding\nan attack. Coiling reflects an eighth\nof the attacker's attack stat",
    "Shadow Hightail" : "Uncontrollable speed and single charge\nfury attacks when an enemy\nis selected",
    "Poison Sting" : "Stings a target. Damage is cut\nthrice, however targets\nare poisoned for 3 seconds",
    "Parasitic Sting" : "Damage is cut thrice, but targets are\npoisoned for 3 seconds. Fury attacks\nlay drones that attack selected bugs",
    "Venom Spray" : "Shoots ranged venom. Damage is cut\nthrice, however targets\nare poisoned for 3 seconds",
    "Venomous Ambush" : "Leaps can be charged by holding\nan attack. Fury attacks poison\nenemies for 3 seconds on landing",
    "Horrendous Ambush" : "Leaps can be charged by holding\nan attack. Fury attacks slow down and\nintimidate enemies for 2 seconds on\nlanding",
    "Dart Ambush" : "Time between attacks is increased\nby 25%, however attacks\nturn into wide-ranging dashes",
    "Specialized Ambush" : "Fury attacks are charged through\nstanding still and camouflauging.\nAttacks turn into wide-ranging leaps",
}

bugStats = {
 Ant:{
 descp: "All around common insects that wander\nlands scouting for food. Their strength\ncomes in numbers and their utility.",
 baseHealth: 45,
 baseAttack: 5,
 baseSpeed: 4,
 skillName: "Mandible Press",
 skillBubble: 9,
 swimAble: false,
 flyAble: false,
 rarity: "Common",
 cropY: -6,
 image: imgMake("Ant"),
 obtained: false,
},
 Termite:{
 descp: "Destructive pests that can build enormous\nnests. When in danger they can spit an acidic\nsolution stopping attackers in their tracks.",
 baseHealth: 40,
 baseAttack: 5.625,
 baseSpeed: 4,
 skillName: "Saliva Salvo",
 skillBubble: 15,
 swimAble: false,
 flyAble: false,
 rarity: "Common",
 cropY: 0,
 image: imgMake("Termite"),
 obtained: false,
},
 Fly:{
 descp: "Repulsive flying insects that do not\npose much of a threat. Their saliva\nis utterly repulsive.",
 baseHealth: 35,
 baseAttack: 5,
 baseSpeed: 4.8,
 skillName: "Saliva Salvo",
 skillBubble: 15,
 swimAble: false,
 flyAble: true,
 rarity: "Common",
 cropY: -6,
 image: imgMake("Fly"),
 obtained: false,
},
 Wriggler:{
 descp: "Careless and insignificant. They wait in\nshallow waters until its time for their\nvengeanace.",
 baseHealth: 30,
 baseAttack: 5.625,
 baseSpeed: 2.8,
 skillName: "???",
 skillBubble: 61,
 swimAble: true,
 flyAble: false,
 rarity: "Common",
 cropY: -30,
 image: imgMake("Wriggler"),
 evolve: "Mosquito",
 obtained: false,
},
 Mosquito:{
 descp: "Remarkably fragile, their lives depend\non their parasitic nature of using their\nhosts to feed the next generation.",
 baseHealth: 30,
 baseAttack: 5.625,
 baseSpeed: 4.8,
 skillName: "Life Meal",
 skillBubble: 61,
 swimAble: false,
 flyAble: true,
 rarity: "Common",
 cropY: -5,
 image: imgMake("Mosquito"),
 offspring: "Wriggler",
 obtained: false,
},
 Water_Tiger:{
 descp: "Small menacing larvae that are vicious\npredators in water where most\nbugs do not pose a threat.",
 baseHealth: 45,
 baseAttack: 5.625,
 baseSpeed: 2.8,
 skillName: "???",
 skillBubble: 9,
 swimAble: true,
 flyAble: false,
 rarity: "Common",
 cropY: 0,
 image: imgMake("WaterTiger"),
 evolve: "Diving_Beetle",
 obtained: false,
},
 Diving_Beetle:{
 descp: "Slow hulking beetles that are laughably slow.\nIn water however, they have an advantage\nagainst non-swimmers.",
 baseHealth: 60,
 baseAttack: 6.875,
 baseSpeed: 2.8,
 skillName: "Mandible Press",
 skillBubble: 9,
 swimAble: true,
 flyAble: true,
 rarity: "Common",
 cropY: 0,
 image: imgMake("DivingBeetle"),
 offspring: "Water_Tiger",
 obtained: false,
},
 Pondskater:{
 descp: "Fast and graceful bugs that can leap to safety\nwhen in danger. Non-swimmers are no match\nfor these bugs once they enter water.",
 baseHealth: 55,
 baseAttack: 6.25,
 baseSpeed: 6,
 skillName: "Dart Ambush",
 skillBubble: 19,
 swimAble: true,
 flyAble: true,
 rarity: "Rare",
 cropY: -40,
 image: imgMake("Pondskater"),
 obtained: false,
},
 Glowworm:{
 descp: "Ground dwelling larvae that undergo countless\nyears of hunting before becoming\nlights in the night.",
 baseHealth: 45,
 baseAttack: 7.5,
 baseSpeed: 4.4,
 skillName: "???",
 skillBubble: 62,
 swimAble: false,
 flyAble: false,
 rarity: "Rare",
 cropY: -60,
 image: imgMake("Glowworm"),
 evolve: "Firefly",
 obtained: false,
},
 Firefly:{
 descp: "Breathtaking beetles that dot the night\nsky with their brilliant bioluminescent lights.",
 baseHealth: 55,
 baseAttack: 6.875,
 baseSpeed: 4.8,
 skillName: "Noxious Whimper",
 skillBubble: 62,
 swimAble: false,
 flyAble: true,
 rarity: "Rare",
 cropY: -40,
 image: imgMake("Firefly"),
 offspring: "Glowworm",
 obtained: false,
},
 Caterpillar:{
 descp: "Vibrant larvae that take shelter in\nfoliage eating whatever they can to aid\ntheir puny bodies in metamorphosis.",
 baseHealth: 60,
 baseAttack: 6.875,
 baseSpeed: 3.6,
 skillName: "???",
 skillBubble: 62,
 swimAble: false,
 flyAble: false,
 rarity: "Rare",
 cropY: -40,
 image: imgMake("Caterpillar"),
 evolve: "Butterfly",
 obtained: false,
},
 Butterfly:{
 descp: "Majestic insects with versatile patterns,\nand a rather clumsy trudge. Although, they\nprefer not to walk.",
 baseHealth: 55,
 baseAttack: 6.875,
 baseSpeed: 4.8,
 skillName: "Noxious Whimper",
 skillBubble: 62,
 swimAble: false,
 flyAble: true,
 rarity: "Rare",
 cropY: 5,
 image: imgMake("Butterfly"),
 offspring: "Caterpillar",
 obtained: false,
},
 Bed_Bug:{
 descp: "Hardy parasites that cause psychological\nharm. If need be, they don't have to feed\nfor years.",
 baseHealth: 70,
 baseAttack: 7.5,
 baseSpeed: 4.8,
 skillName: "Life Meal",
 skillBubble: 61,
 swimAble: false,
 flyAble: false,
 rarity: "Rare",
 cropY: -20,
 image: imgMake("BedBug"),
 obtained: false,
},
 Bee:{
 descp: "Peaceful bugs capable of using an insidious\npoison that leads to a slow and painful death.",
 baseHealth: 60,
 baseAttack: 6.25,
 baseSpeed: 6,
 skillName: "Poison Sting",
 skillBubble: 21,
 swimAble: false,
 flyAble: true,
 rarity: "Rare",
 cropY: -20,
 image: imgMake("Bee"),
 obtained: false,
},
 Weta:{
 descp: "Large flightless bugs. When\nchallenged by other bugs that ignore their\nmassive size, they quickly attempt\nto intimidate them and flee.",
 baseHealth: 85,
 baseAttack: 9.375,
 baseSpeed: 6,
 skillName: "Stridulating Retreat",
 skillBubble: 54,
 swimAble: false,
 flyAble: false,
 rarity: "Epic",
 cropY: 0,
 image: imgMake("Weta"),
 obtained: false,
},
 Mantis:{
 descp: "Devout fragile looking ambushers. They\nprefer to disappear into their surroundings\nand wait for unsuspecting prey.",
 baseHealth: 65,
 baseAttack: 9.375,
 baseSpeed: 6.4,
 skillName: "Specialized Ambush",
 skillBubble: 57,
 swimAble: false,
 flyAble: false,
 rarity: "Epic",
 cropY: -3,
 image: imgMake("Mantis"),
 obtained: false,
},
 Scorpion:{
 descp: "Small arachnoid creatures that sport large tails\nthat shoot noxious venom at range.\nAlthough, they prefer to use it as last resort.",
 baseHealth: 80,
 baseAttack: 8.125,
 baseSpeed: 6.4,
 skillName: "Venom Spray",
 skillBubble: 49,
 swimAble: false,
 flyAble: false,
 rarity: "Epic",
 cropY: 50,
 image: imgMake("Scorpion"),
 obtained: false,
},
 Spider:{
 descp: "Smart and crafty arachnoids. Their graceful\nleaps leave their prey in awe before\ninevitably being pounced and poisoned.",
 baseHealth: 80,
 baseAttack: 9.375,
 baseSpeed: 5.6,
 skillName: "Venomous Ambush",
 skillBubble: 50,
 swimAble: false,
 flyAble: false,
 rarity: "Epic",
 cropY: 0,
 image: imgMake("Spider"),
 obtained: false,
},
 Millipede:{
 descp: "Bulky arthropods that are remarkably passive\ncompared to other predatory arthropods.\nThey curl-up at the immediate site of danger.",
 baseHealth: 100,
 baseAttack: 5,
 baseSpeed: 5.6,
 skillName: "Defensive Coil",
 skillBubble: 56,
 swimAble: false,
 flyAble: false,
 rarity: "Epic",
 cropY: -5,
 image: imgMake("Millipede"),
 obtained: false,
},
 Centipede:{
 descp: "Slender predators that are among the\nlargest invertebrates. A slight twitch\nfrom their finely tuned antennae means\nhavoc for all that is near.",
 baseHealth: 85,
 baseAttack: 11.25,
 baseSpeed: 6.8,
 skillName: "Shadow Hightail",
 skillBubble: 46,
 swimAble: false,
 flyAble: false,
 rarity: "Legendary",
 cropY: 0,
 image: imgMake("Centipede"),
 obtained: false,
},
 Tarantula:{
 descp: "Horrifying and deadly arachnoids. Their\ngraceless leaps leave their prey in fear\nbefore inevitably falling to their doom.",
 baseHealth: 90,
 baseAttack: 10.625,
 baseSpeed: 6.4,
 skillName: "Horrendous Ambush",
 skillBubble: 69,
 swimAble: false,
 flyAble: false,
 rarity: "Legendary",
 cropY: 0,
 image: imgMake("Tarantula"),
 obtained: false,
},
 Wasp:{
 descp: "Merciless hunters that prey on the weak\nwith a lethal poison. Their victims are\nleft with a gift containing hungry larvae.",
 baseHealth: 85,
 baseAttack: 11.875,
 baseSpeed: 7.2,
 skillName: "Parasitic Sting",
 skillBubble: 48,
 swimAble: false,
 flyAble: true,
 rarity: "Legendary",
 cropY: 0,
 image: imgMake("Wasp"),
 obtained: false,
},
 Giant_Water_Bug:{
 descp: "Feared by many, giant water bugs have\nplenty of tools under their belts most of\nwhich are for tackling creatures much\nlarger than themselves.",
 baseHealth: 90,
 baseAttack: 12.5,
 baseSpeed: 6.4,
 skillName: "Specialized Ambush",
 skillBubble: 57,
 swimAble: true,
 flyAble: true,
 rarity: "Legendary",
 cropY: 1,
 image: imgMake("GiantWaterBug"),
 obtained: false,
},
 Dragonfly_Nymph:{
 descp: "Even as dragonfly nymphs, these larvae will\npursue pests. After metamorphosis their\ncunning speeds makes their meals almost\nsport.",
 baseHealth: 90,
 baseAttack: 10.625,
 baseSpeed: 6.4,
 skillName: "???",
 skillBubble: 19,
 swimAble: true,
 flyAble: false,
 rarity: "Legendary",
 cropY: -25,
 image: imgMake("DragonflyNymph"),
 evolve: "Dragonfly",
 obtained: false,
},
 Dragonfly:{
 descp: "Ruthless brutes that dive and grab prey,\noftentimes adult mosquitoes, and tear\nthem apart.",
 baseHealth: 85,
 baseAttack: 10,
 baseSpeed: 8,
 skillName: "Dart Ambush",
 skillBubble: 19,
 swimAble: false,
 flyAble: true,
 rarity: "Legendary",
 cropY: -30,
 image: imgMake("Dragonfly"),
 offspring: "Dragonfly_Nymph",
 obtained: false,
}
}
